enable_audio_bell no
window_alert_on_bell no

#Fonts
font_family FiraCode Nerd Font
# font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13

# url
detect_urls yes
url_style straight
open_url_with default

# Theme
# background #1b1b27
# selection_background #ffffff
background_opacity 0.8

# dynamic_background_opacity yes
# background_blur 1 
# active_border_color #7AA2F7
# inactive_border_color #000000

# window padding
window_margin_width 8

# tabs
tab_bar_edge top
tab_bar_margin_width 1.0
tab_bar_margin_height 1.0 0.5
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}"

# styling tabs
active_tab_foreground #0da38a 
active_tab_background #1d202f
active_tab_font_style bold-italic
inactive_tab_foreground #ffffff
inactive_tab_background #292945
inactive_tab_font_style normal

# clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard


include ./themes/Dracula.conf
